version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://hodi:hodi@db:5432/hodi?schema=public
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hodi
      POSTGRES_PASSWORD: hodi
      POSTGRES_DB: hodi
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
