-- AlterTable
ALTER TABLE "Card" ADD COLUMN     "cost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "description" VARCHAR(255),
ALTER COLUMN "attack" SET DEFAULT 0,
ALTER COLUMN "health" SET DEFAULT 1;
